# tomcat 端口
server:
  port: 9001

spring:
  # 数据库
  datasource:
    username: root
    password: gdqhENwd6q95Af18
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sh-cdb-el8935il.sql.tencentcdb.com:63360/ep?useUnicode=true&characterEncoding=utf-8&useSSL=false
    hikari:
      idleTimeout: 5000
      maximumPoolSize: 10
  #api mvc 设置
  mvc:
    throw-exception-if-no-handler-found: true

# 会员设置
member:
  shortUrl:
    salt: I3FqvF
