/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables;


import com.book.core.domain.Book;
import com.book.core.domain.Indexes;
import com.book.core.domain.Keys;
import com.book.core.domain.tables.records.BookSpiderInfoRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 爬虫书籍基础信息表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BookSpiderInfo extends TableImpl<BookSpiderInfoRecord> {

    private static final long serialVersionUID = 511069609;

    /**
     * The reference instance of <code>book.book_spider_info</code>
     */
    public static final BookSpiderInfo BOOK_SPIDER_INFO = new BookSpiderInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookSpiderInfoRecord> getRecordType() {
        return BookSpiderInfoRecord.class;
    }

    /**
     * The column <code>book.book_spider_info.id</code>. 主键
     */
    public final TableField<BookSpiderInfoRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>book.book_spider_info.author_name</code>. 作者
     */
    public final TableField<BookSpiderInfoRecord, String> AUTHOR_NAME = createField("author_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "作者");

    /**
     * The column <code>book.book_spider_info.title</code>. 书名
     */
    public final TableField<BookSpiderInfoRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "书名");

    /**
     * The column <code>book.book_spider_info.tag</code>. 分类标签
     */
    public final TableField<BookSpiderInfoRecord, String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR(255), this, "分类标签");

    /**
     * The column <code>book.book_spider_info.source</code>. 来源
     */
    public final TableField<BookSpiderInfoRecord, String> SOURCE = createField("source", org.jooq.impl.SQLDataType.VARCHAR(255), this, "来源");

    /**
     * The column <code>book.book_spider_info.url</code>. 来源链接
     */
    public final TableField<BookSpiderInfoRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR(255), this, "来源链接");

    /**
     * The column <code>book.book_spider_info.short_desc</code>. 简介
     */
    public final TableField<BookSpiderInfoRecord, String> SHORT_DESC = createField("short_desc", org.jooq.impl.SQLDataType.VARCHAR(3000), this, "简介");

    /**
     * The column <code>book.book_spider_info.img_cover</code>. 封面图片
     */
    public final TableField<BookSpiderInfoRecord, String> IMG_COVER = createField("img_cover", org.jooq.impl.SQLDataType.VARCHAR(255), this, "封面图片");

    /**
     * The column <code>book.book_spider_info.create_at</code>. 创建时间
     */
    public final TableField<BookSpiderInfoRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>book.book_spider_info.update_at</code>. 更新时间
     */
    public final TableField<BookSpiderInfoRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");

    /**
     * The column <code>book.book_spider_info.remark</code>. 备注
     */
    public final TableField<BookSpiderInfoRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR(255), this, "备注");

    /**
     * The column <code>book.book_spider_info.del_flag</code>. 删除标记
     */
    public final TableField<BookSpiderInfoRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "删除标记");

    /**
     * The column <code>book.book_spider_info.version</code>. 版本号
     */
    public final TableField<BookSpiderInfoRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "版本号");

    /**
     * Create a <code>book.book_spider_info</code> table reference
     */
    public BookSpiderInfo() {
        this(DSL.name("book_spider_info"), null);
    }

    /**
     * Create an aliased <code>book.book_spider_info</code> table reference
     */
    public BookSpiderInfo(String alias) {
        this(DSL.name(alias), BOOK_SPIDER_INFO);
    }

    /**
     * Create an aliased <code>book.book_spider_info</code> table reference
     */
    public BookSpiderInfo(Name alias) {
        this(alias, BOOK_SPIDER_INFO);
    }

    private BookSpiderInfo(Name alias, Table<BookSpiderInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookSpiderInfo(Name alias, Table<BookSpiderInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "爬虫书籍基础信息表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Book.BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_SPIDER_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookSpiderInfoRecord, Long> getIdentity() {
        return Keys.IDENTITY_BOOK_SPIDER_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookSpiderInfoRecord> getPrimaryKey() {
        return Keys.KEY_BOOK_SPIDER_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookSpiderInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<BookSpiderInfoRecord>>asList(Keys.KEY_BOOK_SPIDER_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<BookSpiderInfoRecord, Long> getRecordVersion() {
        return VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookSpiderInfo as(String alias) {
        return new BookSpiderInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookSpiderInfo as(Name alias) {
        return new BookSpiderInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookSpiderInfo rename(String name) {
        return new BookSpiderInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookSpiderInfo rename(Name name) {
        return new BookSpiderInfo(name, null);
    }
}
