/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables;


import com.book.core.domain.Book;
import com.book.core.domain.Indexes;
import com.book.core.domain.Keys;
import com.book.core.domain.tables.records.BookThirdCopyrightInfoRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 第三方版权书籍基础信息表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BookThirdCopyrightInfo extends TableImpl<BookThirdCopyrightInfoRecord> {

    /**
     * The reference instance of <code>book.book_third_copyright_info</code>
     */
    public static final BookThirdCopyrightInfo BOOK_THIRD_COPYRIGHT_INFO = new BookThirdCopyrightInfo();
    private static final long serialVersionUID = -233399025;
    /**
     * The column <code>book.book_third_copyright_info.id</code>. 主键
     */
    public final TableField<BookThirdCopyrightInfoRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键");
    /**
     * The column <code>book.book_third_copyright_info.author_name</code>. 作者
     */
    public final TableField<BookThirdCopyrightInfoRecord, String> AUTHOR_NAME = createField("author_name", org.jooq.impl.SQLDataType.VARCHAR(64), this, "作者");
    /**
     * The column <code>book.book_third_copyright_info.title</code>. 书名
     */
    public final TableField<BookThirdCopyrightInfoRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "书名");
    /**
     * The column <code>book.book_third_copyright_info.tag</code>. 分类标签
     */
    public final TableField<BookThirdCopyrightInfoRecord, String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR(255), this, "分类标签");
    /**
     * The column <code>book.book_third_copyright_info.copyright_name</code>. 版权方
     */
    public final TableField<BookThirdCopyrightInfoRecord, String> COPYRIGHT_NAME = createField("copyright_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "版权方");
    /**
     * The column <code>book.book_third_copyright_info.url</code>. 来源链接
     */
    public final TableField<BookThirdCopyrightInfoRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR(255), this, "来源链接");
    /**
     * The column <code>book.book_third_copyright_info.short_desc</code>. 简介
     */
    public final TableField<BookThirdCopyrightInfoRecord, String> SHORT_DESC = createField("short_desc", org.jooq.impl.SQLDataType.VARCHAR(3000), this, "简介");
    /**
     * The column <code>book.book_third_copyright_info.img_cover</code>. 封面图片
     */
    public final TableField<BookThirdCopyrightInfoRecord, String> IMG_COVER = createField("img_cover", org.jooq.impl.SQLDataType.VARCHAR(255), this, "封面图片");
    /**
     * The column <code>book.book_third_copyright_info.create_at</code>. 创建时间
     */
    public final TableField<BookThirdCopyrightInfoRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");
    /**
     * The column <code>book.book_third_copyright_info.update_at</code>. 更新时间
     */
    public final TableField<BookThirdCopyrightInfoRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");
    /**
     * The column <code>book.book_third_copyright_info.remark</code>. 备注
     */
    public final TableField<BookThirdCopyrightInfoRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR(255), this, "备注");
    /**
     * The column <code>book.book_third_copyright_info.del_flag</code>. 删除标记
     */
    public final TableField<BookThirdCopyrightInfoRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "删除标记");
    /**
     * The column <code>book.book_third_copyright_info.version</code>. 版本号
     */
    public final TableField<BookThirdCopyrightInfoRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "版本号");

    /**
     * Create a <code>book.book_third_copyright_info</code> table reference
     */
    public BookThirdCopyrightInfo() {
        this(DSL.name("book_third_copyright_info"), null);
    }

    /**
     * Create an aliased <code>book.book_third_copyright_info</code> table reference
     */
    public BookThirdCopyrightInfo(String alias) {
        this(DSL.name(alias), BOOK_THIRD_COPYRIGHT_INFO);
    }

    /**
     * Create an aliased <code>book.book_third_copyright_info</code> table reference
     */
    public BookThirdCopyrightInfo(Name alias) {
        this(alias, BOOK_THIRD_COPYRIGHT_INFO);
    }

    private BookThirdCopyrightInfo(Name alias, Table<BookThirdCopyrightInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private BookThirdCopyrightInfo(Name alias, Table<BookThirdCopyrightInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "第三方版权书籍基础信息表");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BookThirdCopyrightInfoRecord> getRecordType() {
        return BookThirdCopyrightInfoRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Book.BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BOOK_THIRD_COPYRIGHT_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BookThirdCopyrightInfoRecord, Long> getIdentity() {
        return Keys.IDENTITY_BOOK_THIRD_COPYRIGHT_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BookThirdCopyrightInfoRecord> getPrimaryKey() {
        return Keys.KEY_BOOK_THIRD_COPYRIGHT_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BookThirdCopyrightInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<BookThirdCopyrightInfoRecord>>asList(Keys.KEY_BOOK_THIRD_COPYRIGHT_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<BookThirdCopyrightInfoRecord, Long> getRecordVersion() {
        return VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookThirdCopyrightInfo as(String alias) {
        return new BookThirdCopyrightInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookThirdCopyrightInfo as(Name alias) {
        return new BookThirdCopyrightInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BookThirdCopyrightInfo rename(String name) {
        return new BookThirdCopyrightInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BookThirdCopyrightInfo rename(Name name) {
        return new BookThirdCopyrightInfo(name, null);
    }
}
