/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables;


import com.book.core.domain.Book;
import com.book.core.domain.Indexes;
import com.book.core.domain.Keys;
import com.book.core.domain.tables.records.MemberBookCollectionRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * 会员书籍收藏表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MemberBookCollection extends TableImpl<MemberBookCollectionRecord> {

    /**
     * The reference instance of <code>book.member_book_collection</code>
     */
    public static final MemberBookCollection MEMBER_BOOK_COLLECTION = new MemberBookCollection();
    private static final long serialVersionUID = 1157741702;
    /**
     * The column <code>book.member_book_collection.id</code>. 主键
     */
    public final TableField<MemberBookCollectionRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "主键");
    /**
     * The column <code>book.member_book_collection.member_id</code>. 会员id
     */
    public final TableField<MemberBookCollectionRecord, Long> MEMBER_ID = createField("member_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "会员id");
    /**
     * The column <code>book.member_book_collection.book_id</code>. 书籍id
     */
    public final TableField<MemberBookCollectionRecord, Long> BOOK_ID = createField("book_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "书籍id");
    /**
     * The column <code>book.member_book_collection.remark</code>. 备注
     */
    public final TableField<MemberBookCollectionRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.VARCHAR(255), this, "备注");
    /**
     * The column <code>book.member_book_collection.create_at</code>. 创建时间
     */
    public final TableField<MemberBookCollectionRecord, Timestamp> CREATE_AT = createField("create_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");
    /**
     * The column <code>book.member_book_collection.update_at</code>. 更新时间
     */
    public final TableField<MemberBookCollectionRecord, Timestamp> UPDATE_AT = createField("update_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新时间");
    /**
     * The column <code>book.member_book_collection.del_flag</code>. 删除标记
     */
    public final TableField<MemberBookCollectionRecord, Boolean> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.BIT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("b'0'", org.jooq.impl.SQLDataType.BIT)), this, "删除标记");
    /**
     * The column <code>book.member_book_collection.version</code>. 版本号
     */
    public final TableField<MemberBookCollectionRecord, Long> VERSION = createField("version", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "版本号");

    /**
     * Create a <code>book.member_book_collection</code> table reference
     */
    public MemberBookCollection() {
        this(DSL.name("member_book_collection"), null);
    }

    /**
     * Create an aliased <code>book.member_book_collection</code> table reference
     */
    public MemberBookCollection(String alias) {
        this(DSL.name(alias), MEMBER_BOOK_COLLECTION);
    }

    /**
     * Create an aliased <code>book.member_book_collection</code> table reference
     */
    public MemberBookCollection(Name alias) {
        this(alias, MEMBER_BOOK_COLLECTION);
    }

    private MemberBookCollection(Name alias, Table<MemberBookCollectionRecord> aliased) {
        this(alias, aliased, null);
    }

    private MemberBookCollection(Name alias, Table<MemberBookCollectionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "会员书籍收藏表");
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MemberBookCollectionRecord> getRecordType() {
        return MemberBookCollectionRecord.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Book.BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.MEMBER_BOOK_COLLECTION_INDEX_MEMBER_ID, Indexes.MEMBER_BOOK_COLLECTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MemberBookCollectionRecord, Long> getIdentity() {
        return Keys.IDENTITY_MEMBER_BOOK_COLLECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MemberBookCollectionRecord> getPrimaryKey() {
        return Keys.KEY_MEMBER_BOOK_COLLECTION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MemberBookCollectionRecord>> getKeys() {
        return Arrays.<UniqueKey<MemberBookCollectionRecord>>asList(Keys.KEY_MEMBER_BOOK_COLLECTION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TableField<MemberBookCollectionRecord, Long> getRecordVersion() {
        return VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollection as(String alias) {
        return new MemberBookCollection(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollection as(Name alias) {
        return new MemberBookCollection(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberBookCollection rename(String name) {
        return new MemberBookCollection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MemberBookCollection rename(Name name) {
        return new MemberBookCollection(name, null);
    }
}
