/*
 * This file is generated by jOOQ.
*/
package com.book.core.domain.tables.records;


import com.book.core.domain.enums.AuthorityTokenTarget;
import com.book.core.domain.tables.AuthorityToken;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 鉴权登录表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuthorityTokenRecord extends UpdatableRecordImpl<AuthorityTokenRecord> implements Record12<Long, Long, AuthorityTokenTarget, Long, String, Timestamp, String, Timestamp, Timestamp, String, Boolean, Long> {

    private static final long serialVersionUID = 925145697;

    /**
     * Create a detached AuthorityTokenRecord
     */
    public AuthorityTokenRecord() {
        super(AuthorityToken.AUTHORITY_TOKEN);
    }

    /**
     * Create a detached, initialised AuthorityTokenRecord
     */
    public AuthorityTokenRecord(Long id, Long targetId, AuthorityTokenTarget target, Long clientId, String accessIp, Timestamp expireTime, String code, Timestamp createAt, Timestamp updateAt, String remark, Boolean delFlag, Long version) {
        super(AuthorityToken.AUTHORITY_TOKEN);

        set(0, id);
        set(1, targetId);
        set(2, target);
        set(3, clientId);
        set(4, accessIp);
        set(5, expireTime);
        set(6, code);
        set(7, createAt);
        set(8, updateAt);
        set(9, remark);
        set(10, delFlag);
        set(11, version);
    }

    /**
     * Getter for <code>book.authority_token.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book.authority_token.id</code>. 主键
     */
    public AuthorityTokenRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.target_id</code>. 鉴权主体id
     */
    public Long getTargetId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book.authority_token.target_id</code>. 鉴权主体id
     */
    public AuthorityTokenRecord setTargetId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.target</code>. 鉴权登录对象：会员；平台；
     */
    public AuthorityTokenTarget getTarget() {
        return (AuthorityTokenTarget) get(2);
    }

    /**
     * Setter for <code>book.authority_token.target</code>. 鉴权登录对象：会员；平台；
     */
    public AuthorityTokenRecord setTarget(AuthorityTokenTarget value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.client_id</code>. 鉴权客户端id
     */
    public Long getClientId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>book.authority_token.client_id</code>. 鉴权客户端id
     */
    public AuthorityTokenRecord setClientId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.access_ip</code>. 创建ip
     */
    public String getAccessIp() {
        return (String) get(4);
    }

    /**
     * Setter for <code>book.authority_token.access_ip</code>. 创建ip
     */
    public AuthorityTokenRecord setAccessIp(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.expire_time</code>. 过期时间
     */
    public Timestamp getExpireTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>book.authority_token.expire_time</code>. 过期时间
     */
    public AuthorityTokenRecord setExpireTime(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.code</code>. token串
     */
    public String getCode() {
        return (String) get(6);
    }

    /**
     * Setter for <code>book.authority_token.code</code>. token串
     */
    public AuthorityTokenRecord setCode(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>book.authority_token.create_at</code>. 创建时间
     */
    public AuthorityTokenRecord setCreateAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>book.authority_token.update_at</code>. 更新时间
     */
    public AuthorityTokenRecord setUpdateAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(9);
    }

    /**
     * Setter for <code>book.authority_token.remark</code>. 备注
     */
    public AuthorityTokenRecord setRemark(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>book.authority_token.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>book.authority_token.del_flag</code>. 删除标记
     */
    public AuthorityTokenRecord setDelFlag(Boolean value) {
        set(10, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>book.authority_token.version</code>.
     */
    public Long getVersion() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>book.authority_token.version</code>.
     */
    public AuthorityTokenRecord setVersion(Long value) {
        set(11, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, AuthorityTokenTarget, Long, String, Timestamp, String, Timestamp, Timestamp, String, Boolean, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, AuthorityTokenTarget, Long, String, Timestamp, String, Timestamp, Timestamp, String, Boolean, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return AuthorityToken.AUTHORITY_TOKEN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return AuthorityToken.AUTHORITY_TOKEN.TARGET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<AuthorityTokenTarget> field3() {
        return AuthorityToken.AUTHORITY_TOKEN.TARGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return AuthorityToken.AUTHORITY_TOKEN.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return AuthorityToken.AUTHORITY_TOKEN.ACCESS_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return AuthorityToken.AUTHORITY_TOKEN.EXPIRE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return AuthorityToken.AUTHORITY_TOKEN.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return AuthorityToken.AUTHORITY_TOKEN.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return AuthorityToken.AUTHORITY_TOKEN.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return AuthorityToken.AUTHORITY_TOKEN.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return AuthorityToken.AUTHORITY_TOKEN.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return AuthorityToken.AUTHORITY_TOKEN.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenTarget component3() {
        return getTarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAccessIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTargetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenTarget value3() {
        return getTarget();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAccessIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value2(Long value) {
        setTargetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value3(AuthorityTokenTarget value) {
        setTarget(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value4(Long value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value5(String value) {
        setAccessIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value6(Timestamp value) {
        setExpireTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value7(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value8(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value9(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value10(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value11(Boolean value) {
        setDelFlag(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord value12(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorityTokenRecord values(Long value1, Long value2, AuthorityTokenTarget value3, Long value4, String value5, Timestamp value6, String value7, Timestamp value8, Timestamp value9, String value10, Boolean value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }
}
