/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables.records;


import com.book.core.domain.tables.BookBaseClassification;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 书籍分类表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class BookBaseClassificationRecord extends UpdatableRecordImpl<BookBaseClassificationRecord> implements Record8<Long, String, Long, Timestamp, Timestamp, String, Boolean, Long> {

    private static final long serialVersionUID = -1150080381;

    /**
     * Setter for <code>book.book_base_classification.id</code>. 主键
     */
    public BookBaseClassificationRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Create a detached BookBaseClassificationRecord
     */
    public BookBaseClassificationRecord() {
        super(BookBaseClassification.BOOK_BASE_CLASSIFICATION);
    }

    /**
     * Setter for <code>book.book_base_classification.name</code>. 分类名称
     */
    public BookBaseClassificationRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Create a detached, initialised BookBaseClassificationRecord
     */
    public BookBaseClassificationRecord(Long id, String name, Long sort, Timestamp createAt, Timestamp updateAt, String remark, Boolean delFlag, Long version) {
        super(BookBaseClassification.BOOK_BASE_CLASSIFICATION);

        set(0, id);
        set(1, name);
        set(2, sort);
        set(3, createAt);
        set(4, updateAt);
        set(5, remark);
        set(6, delFlag);
        set(7, version);
    }

    /**
     * Setter for <code>book.book_base_classification.sort</code>. 排序（倒序）
     */
    public BookBaseClassificationRecord setSort(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.book_base_classification.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book.book_base_classification.create_at</code>. 创建时间
     */
    public BookBaseClassificationRecord setCreateAt(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.book_base_classification.name</code>. 分类名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>book.book_base_classification.update_at</code>. 更新时间
     */
    public BookBaseClassificationRecord setUpdateAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.book_base_classification.sort</code>. 排序（倒序）
     */
    public Long getSort() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>book.book_base_classification.remark</code>. 备注
     */
    public BookBaseClassificationRecord setRemark(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.book_base_classification.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(3);
    }

    /**
     * Getter for <code>book.book_base_classification.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(4);
    }

    /**
     * Getter for <code>book.book_base_classification.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(6);
    }

    /**
     * Getter for <code>book.book_base_classification.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Getter for <code>book.book_base_classification.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, Timestamp, Timestamp, String, Boolean, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Long, Timestamp, Timestamp, String, Boolean, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BookBaseClassification.BOOK_BASE_CLASSIFICATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BookBaseClassification.BOOK_BASE_CLASSIFICATION.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return BookBaseClassification.BOOK_BASE_CLASSIFICATION.SORT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return BookBaseClassification.BOOK_BASE_CLASSIFICATION.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return BookBaseClassification.BOOK_BASE_CLASSIFICATION.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BookBaseClassification.BOOK_BASE_CLASSIFICATION.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return BookBaseClassification.BOOK_BASE_CLASSIFICATION.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return BookBaseClassification.BOOK_BASE_CLASSIFICATION.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getSort();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord value3(Long value) {
        setSort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord value4(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord value5(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord value6(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord value7(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord value8(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookBaseClassificationRecord values(Long value1, String value2, Long value3, Timestamp value4, Timestamp value5, String value6, Boolean value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>book.book_base_classification.del_flag</code>. 删除标记
     */
    public BookBaseClassificationRecord setDelFlag(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Setter for <code>book.book_base_classification.version</code>. 版本号
     */
    public BookBaseClassificationRecord setVersion(Long value) {
        set(7, value);
        return this;
    }
}
