/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables.records;


import com.book.core.domain.tables.MemberBookCollection;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 会员书籍收藏表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MemberBookCollectionRecord extends UpdatableRecordImpl<MemberBookCollectionRecord> implements Record8<Long, Long, Long, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = -6119115;

    /**
     * Create a detached MemberBookCollectionRecord
     */
    public MemberBookCollectionRecord() {
        super(MemberBookCollection.MEMBER_BOOK_COLLECTION);
    }

    /**
     * Create a detached, initialised MemberBookCollectionRecord
     */
    public MemberBookCollectionRecord(Long id, Long memberId, Long bookId, String remark, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(MemberBookCollection.MEMBER_BOOK_COLLECTION);

        set(0, id);
        set(1, memberId);
        set(2, bookId);
        set(3, remark);
        set(4, createAt);
        set(5, updateAt);
        set(6, delFlag);
        set(7, version);
    }

    /**
     * Getter for <code>book.member_book_collection.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book.member_book_collection.id</code>. 主键
     */
    public MemberBookCollectionRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_collection.member_id</code>. 会员id
     */
    public Long getMemberId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book.member_book_collection.member_id</code>. 会员id
     */
    public MemberBookCollectionRecord setMemberId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_collection.book_id</code>. 书籍id
     */
    public Long getBookId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>book.member_book_collection.book_id</code>. 书籍id
     */
    public MemberBookCollectionRecord setBookId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_collection.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(3);
    }

    /**
     * Setter for <code>book.member_book_collection.remark</code>. 备注
     */
    public MemberBookCollectionRecord setRemark(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_collection.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>book.member_book_collection.create_at</code>. 创建时间
     */
    public MemberBookCollectionRecord setCreateAt(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_collection.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>book.member_book_collection.update_at</code>. 更新时间
     */
    public MemberBookCollectionRecord setUpdateAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_collection.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>book.member_book_collection.del_flag</code>. 删除标记
     */
    public MemberBookCollectionRecord setDelFlag(Boolean value) {
        set(6, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>book.member_book_collection.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>book.member_book_collection.version</code>. 版本号
     */
    public MemberBookCollectionRecord setVersion(Long value) {
        set(7, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, Long, Long, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MemberBookCollection.MEMBER_BOOK_COLLECTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MemberBookCollection.MEMBER_BOOK_COLLECTION.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return MemberBookCollection.MEMBER_BOOK_COLLECTION.BOOK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MemberBookCollection.MEMBER_BOOK_COLLECTION.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return MemberBookCollection.MEMBER_BOOK_COLLECTION.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MemberBookCollection.MEMBER_BOOK_COLLECTION.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return MemberBookCollection.MEMBER_BOOK_COLLECTION.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return MemberBookCollection.MEMBER_BOOK_COLLECTION.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord value2(Long value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord value3(Long value) {
        setBookId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord value4(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord value5(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord value6(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord value7(Boolean value) {
        setDelFlag(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord value8(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookCollectionRecord values(Long value1, Long value2, Long value3, String value4, Timestamp value5, Timestamp value6, Boolean value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }
}
