/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables.records;


import com.book.core.domain.tables.MemberBookReadLog;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 会员书籍阅读日志表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MemberBookReadLogRecord extends UpdatableRecordImpl<MemberBookReadLogRecord> implements Record9<Long, Long, Long, Long, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = 1497941142;

    /**
     * Create a detached MemberBookReadLogRecord
     */
    public MemberBookReadLogRecord() {
        super(MemberBookReadLog.MEMBER_BOOK_READ_LOG);
    }

    /**
     * Create a detached, initialised MemberBookReadLogRecord
     */
    public MemberBookReadLogRecord(Long id, Long memberId, Long bookId, Long bookCatalogId, String remark, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(MemberBookReadLog.MEMBER_BOOK_READ_LOG);

        set(0, id);
        set(1, memberId);
        set(2, bookId);
        set(3, bookCatalogId);
        set(4, remark);
        set(5, createAt);
        set(6, updateAt);
        set(7, delFlag);
        set(8, version);
    }

    /**
     * Getter for <code>book.member_book_read_log.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book.member_book_read_log.id</code>. 主键
     */
    public MemberBookReadLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_read_log.member_id</code>. 会员id
     */
    public Long getMemberId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book.member_book_read_log.member_id</code>. 会员id
     */
    public MemberBookReadLogRecord setMemberId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_read_log.book_id</code>. 书籍id
     */
    public Long getBookId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>book.member_book_read_log.book_id</code>. 书籍id
     */
    public MemberBookReadLogRecord setBookId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_read_log.book_catalog_id</code>. 目录id
     */
    public Long getBookCatalogId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>book.member_book_read_log.book_catalog_id</code>. 目录id
     */
    public MemberBookReadLogRecord setBookCatalogId(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_read_log.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(4);
    }

    /**
     * Setter for <code>book.member_book_read_log.remark</code>. 备注
     */
    public MemberBookReadLogRecord setRemark(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_read_log.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>book.member_book_read_log.create_at</code>. 创建时间
     */
    public MemberBookReadLogRecord setCreateAt(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_read_log.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>book.member_book_read_log.update_at</code>. 更新时间
     */
    public MemberBookReadLogRecord setUpdateAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book.member_book_read_log.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>book.member_book_read_log.del_flag</code>. 删除标记
     */
    public MemberBookReadLogRecord setDelFlag(Boolean value) {
        set(7, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>book.member_book_read_log.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>book.member_book_read_log.version</code>. 版本号
     */
    public MemberBookReadLogRecord setVersion(Long value) {
        set(8, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Long, Long, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Long, Long, Long, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.BOOK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.BOOK_CATALOG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return MemberBookReadLog.MEMBER_BOOK_READ_LOG.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getBookCatalogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getBookCatalogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value2(Long value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value3(Long value) {
        setBookId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value4(Long value) {
        setBookCatalogId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value5(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value6(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value7(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value8(Boolean value) {
        setDelFlag(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord value9(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBookReadLogRecord values(Long value1, Long value2, Long value3, Long value4, String value5, Timestamp value6, Timestamp value7, Boolean value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }
}
