/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables.records;


import com.book.core.domain.tables.MemberTimePaymentLog;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * 会员时间段付费日志表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MemberTimePaymentLogRecord extends UpdatableRecordImpl<MemberTimePaymentLogRecord> implements Record10<Long, Long, BigDecimal, Timestamp, Timestamp, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = -1844729592;

    /**
     * Setter for <code>book.member_time_payment_log.id</code>. 主键
     */
    public MemberTimePaymentLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Create a detached MemberTimePaymentLogRecord
     */
    public MemberTimePaymentLogRecord() {
        super(MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG);
    }

    /**
     * Setter for <code>book.member_time_payment_log.member_id</code>. 会员id
     */
    public MemberTimePaymentLogRecord setMemberId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Create a detached, initialised MemberTimePaymentLogRecord
     */
    public MemberTimePaymentLogRecord(Long id, Long memberId, BigDecimal realPayAmount, Timestamp startTime, Timestamp endTime, String remark, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG);

        set(0, id);
        set(1, memberId);
        set(2, realPayAmount);
        set(3, startTime);
        set(4, endTime);
        set(5, remark);
        set(6, createAt);
        set(7, updateAt);
        set(8, delFlag);
        set(9, version);
    }

    /**
     * Setter for <code>book.member_time_payment_log.real_pay_amount</code>. 实际支付金额
     */
    public MemberTimePaymentLogRecord setRealPayAmount(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.member_time_payment_log.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book.member_time_payment_log.start_time</code>. 开始时间
     */
    public MemberTimePaymentLogRecord setStartTime(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.member_time_payment_log.member_id</code>. 会员id
     */
    public Long getMemberId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book.member_time_payment_log.end_time</code>. 结束时间
     */
    public MemberTimePaymentLogRecord setEndTime(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.member_time_payment_log.real_pay_amount</code>. 实际支付金额
     */
    public BigDecimal getRealPayAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>book.member_time_payment_log.remark</code>. 备注
     */
    public MemberTimePaymentLogRecord setRemark(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.member_time_payment_log.start_time</code>. 开始时间
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>book.member_time_payment_log.create_at</code>. 创建时间
     */
    public MemberTimePaymentLogRecord setCreateAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book.member_time_payment_log.end_time</code>. 结束时间
     */
    public Timestamp getEndTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>book.member_time_payment_log.update_at</code>. 更新时间
     */
    public MemberTimePaymentLogRecord setUpdateAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>book.member_time_payment_log.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Getter for <code>book.member_time_payment_log.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(6);
    }

    /**
     * Getter for <code>book.member_time_payment_log.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(8);
    }

    /**
     * Getter for <code>book.member_time_payment_log.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(7);
    }

    /**
     * Getter for <code>book.member_time_payment_log.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, BigDecimal, Timestamp, Timestamp, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, BigDecimal, Timestamp, Timestamp, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.REAL_PAY_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return MemberTimePaymentLog.MEMBER_TIME_PAYMENT_LOG.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getRealPayAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getRealPayAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value2(Long value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value3(BigDecimal value) {
        setRealPayAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value4(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value5(Timestamp value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value6(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value7(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value8(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value9(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord value10(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberTimePaymentLogRecord values(Long value1, Long value2, BigDecimal value3, Timestamp value4, Timestamp value5, String value6, Timestamp value7, Timestamp value8, Boolean value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>book.member_time_payment_log.del_flag</code>. 删除标志
     */
    public MemberTimePaymentLogRecord setDelFlag(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Setter for <code>book.member_time_payment_log.version</code>. 版本号
     */
    public MemberTimePaymentLogRecord setVersion(Long value) {
        set(9, value);
        return this;
    }
}
