/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables.records;


import com.book.core.domain.enums.MemberCapitalInOutLogAmountType;
import com.book.core.domain.enums.MemberCapitalInOutLogType;
import com.book.core.domain.tables.MemberCapitalInOutLog;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Timestamp;


/**
 * 会员资金流水表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MemberCapitalInOutLogRecord extends UpdatableRecordImpl<MemberCapitalInOutLogRecord> implements Record12<Long, Long, BigDecimal, MemberCapitalInOutLogType, BigDecimal, MemberCapitalInOutLogAmountType, String, String, Timestamp, Boolean, Timestamp, Long> {

    private static final long serialVersionUID = -1123207329;

    /**
     * Setter for <code>book.member_capital_in_out_log.id</code>.
     */
    public MemberCapitalInOutLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Create a detached MemberCapitalInOutLogRecord
     */
    public MemberCapitalInOutLogRecord() {
        super(MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.member_id</code>. 会员标识
     */
    public MemberCapitalInOutLogRecord setMemberId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Create a detached, initialised MemberCapitalInOutLogRecord
     */
    public MemberCapitalInOutLogRecord(Long id, Long memberId, BigDecimal availableBalance, MemberCapitalInOutLogType type, BigDecimal amount, MemberCapitalInOutLogAmountType amountType, String sourceId, String remark, Timestamp createAt, Boolean delFlag, Timestamp updateAt, Long version) {
        super(MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG);

        set(0, id);
        set(1, memberId);
        set(2, availableBalance);
        set(3, type);
        set(4, amount);
        set(5, amountType);
        set(6, sourceId);
        set(7, remark);
        set(8, createAt);
        set(9, delFlag);
        set(10, updateAt);
        set(11, version);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.available_balance</code>. 变更后可用余额
     */
    public MemberCapitalInOutLogRecord setAvailableBalance(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.type</code>. 类型：充值、vip购买
     */
    public MemberCapitalInOutLogRecord setType(MemberCapitalInOutLogType value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.member_id</code>. 会员标识
     */
    public Long getMemberId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.amount</code>. 交易金额
     */
    public MemberCapitalInOutLogRecord setAmount(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.available_balance</code>. 变更后可用余额
     */
    public BigDecimal getAvailableBalance() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.amount_type</code>. 收入、支出
     */
    public MemberCapitalInOutLogRecord setAmountType(MemberCapitalInOutLogAmountType value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.type</code>. 类型：充值、vip购买
     */
    public MemberCapitalInOutLogType getType() {
        return (MemberCapitalInOutLogType) get(3);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.source_id</code>. 业务id：充值记录id；vip购买记录id；
     */
    public MemberCapitalInOutLogRecord setSourceId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.amount</code>. 交易金额
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.remark</code>.
     */
    public MemberCapitalInOutLogRecord setRemark(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.amount_type</code>. 收入、支出
     */
    public MemberCapitalInOutLogAmountType getAmountType() {
        return (MemberCapitalInOutLogAmountType) get(5);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.create_at</code>. 创建时间
     */
    public MemberCapitalInOutLogRecord setCreateAt(Timestamp value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.del_flag</code>. 删除标记
     */
    public MemberCapitalInOutLogRecord setDelFlag(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.source_id</code>. 业务id：充值记录id；vip购买记录id；
     */
    public String getSourceId() {
        return (String) get(6);
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.remark</code>.
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.del_flag</code>. 删除标记
     */
    public Boolean getDelFlag() {
        return (Boolean) get(9);
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(10);
    }

    /**
     * Getter for <code>book.member_capital_in_out_log.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, BigDecimal, MemberCapitalInOutLogType, BigDecimal, MemberCapitalInOutLogAmountType, String, String, Timestamp, Boolean, Timestamp, Long> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Long, Long, BigDecimal, MemberCapitalInOutLogType, BigDecimal, MemberCapitalInOutLogAmountType, String, String, Timestamp, Boolean, Timestamp, Long> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.AVAILABLE_BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<MemberCapitalInOutLogType> field4() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<MemberCapitalInOutLogAmountType> field6() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.AMOUNT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.SOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return MemberCapitalInOutLog.MEMBER_CAPITAL_IN_OUT_LOG.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getAvailableBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogType component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogAmountType component6() {
        return getAmountType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getAvailableBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogType value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogAmountType value6() {
        return getAmountType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value2(Long value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value3(BigDecimal value) {
        setAvailableBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value4(MemberCapitalInOutLogType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value5(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value6(MemberCapitalInOutLogAmountType value) {
        setAmountType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value7(String value) {
        setSourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value8(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value9(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value10(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value11(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord value12(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberCapitalInOutLogRecord values(Long value1, Long value2, BigDecimal value3, MemberCapitalInOutLogType value4, BigDecimal value5, MemberCapitalInOutLogAmountType value6, String value7, String value8, Timestamp value9, Boolean value10, Timestamp value11, Long value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>book.member_capital_in_out_log.update_at</code>. 更新时间
     */
    public MemberCapitalInOutLogRecord setUpdateAt(Timestamp value) {
        set(10, value);
        return this;
    }

    /**
     * Setter for <code>book.member_capital_in_out_log.version</code>. 版本号
     */
    public MemberCapitalInOutLogRecord setVersion(Long value) {
        set(11, value);
        return this;
    }
}
