/*
 * This file is generated by jOOQ.
*/
package com.book.core.domain.tables.records;


import com.book.core.domain.enums.MemberBaseInfoSex;
import com.book.core.domain.enums.MemberBaseInfoStatus;
import com.book.core.domain.tables.MemberBaseInfo;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 会员基础信息表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MemberBaseInfoRecord extends UpdatableRecordImpl<MemberBaseInfoRecord> implements Record20<Long, Long, MemberBaseInfoStatus, Timestamp, MemberBaseInfoSex, Timestamp, String, String, String, String, Long, String, String, Timestamp, String, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = -1390701089;

    /**
     * Setter for <code>book.member_base_info.id</code>. 主键
     */
    public MemberBaseInfoRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Create a detached MemberBaseInfoRecord
     */
    public MemberBaseInfoRecord() {
        super(MemberBaseInfo.MEMBER_BASE_INFO);
    }

    /**
     * Setter for <code>book.member_base_info.mobile</code>. 手机号
     */
    public MemberBaseInfoRecord setMobile(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Create a detached, initialised MemberBaseInfoRecord
     */
    public MemberBaseInfoRecord(Long id, Long mobile, MemberBaseInfoStatus status, Timestamp timePaymentEnd, MemberBaseInfoSex sex, Timestamp birthday, String trueName, String identityNumber, String shortUrl, String avatar, Long registerClient, String registerTraceSource, String registerTraceNo, Timestamp registerTime, String registerIp, String remark, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(MemberBaseInfo.MEMBER_BASE_INFO);

        set(0, id);
        set(1, mobile);
        set(2, status);
        set(3, timePaymentEnd);
        set(4, sex);
        set(5, birthday);
        set(6, trueName);
        set(7, identityNumber);
        set(8, shortUrl);
        set(9, avatar);
        set(10, registerClient);
        set(11, registerTraceSource);
        set(12, registerTraceNo);
        set(13, registerTime);
        set(14, registerIp);
        set(15, remark);
        set(16, createAt);
        set(17, updateAt);
        set(18, delFlag);
        set(19, version);
    }

    /**
     * Setter for <code>book.member_base_info.status</code>. 状态：正常；已冻结；已注销；
     */
    public MemberBaseInfoRecord setStatus(MemberBaseInfoStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Getter for <code>book.member_base_info.mobile</code>. 手机号
     */
    public Long getMobile() {
        return (Long) get(1);
    }

    /**
     * Getter for <code>book.member_base_info.status</code>. 状态：正常；已冻结；已注销；
     */
    public MemberBaseInfoStatus getStatus() {
        return (MemberBaseInfoStatus) get(2);
    }

    /**
     * Getter for <code>book.member_base_info.time_payment_end</code>. 付费截至时间
     */
    public Timestamp getTimePaymentEnd() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>book.member_base_info.time_payment_end</code>. 付费截至时间
     */
    public MemberBaseInfoRecord setTimePaymentEnd(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.sex</code>. 性别：男；女；未知；
     */
    public MemberBaseInfoSex getSex() {
        return (MemberBaseInfoSex) get(4);
    }

    /**
     * Setter for <code>book.member_base_info.sex</code>. 性别：男；女；未知；
     */
    public MemberBaseInfoRecord setSex(MemberBaseInfoSex value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.birthday</code>. 生日
     */
    public Timestamp getBirthday() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>book.member_base_info.birthday</code>. 生日
     */
    public MemberBaseInfoRecord setBirthday(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.true_name</code>. 真实姓名
     */
    public String getTrueName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>book.member_base_info.true_name</code>. 真实姓名
     */
    public MemberBaseInfoRecord setTrueName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.identity_number</code>. 身份证号码
     */
    public String getIdentityNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>book.member_base_info.identity_number</code>. 身份证号码
     */
    public MemberBaseInfoRecord setIdentityNumber(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.short_url</code>. 推荐码
     */
    public String getShortUrl() {
        return (String) get(8);
    }

    /**
     * Setter for <code>book.member_base_info.short_url</code>. 推荐码
     */
    public MemberBaseInfoRecord setShortUrl(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.avatar</code>. 个人头像url
     */
    public String getAvatar() {
        return (String) get(9);
    }

    /**
     * Setter for <code>book.member_base_info.avatar</code>. 个人头像url
     */
    public MemberBaseInfoRecord setAvatar(String value) {
        set(9, value);
        return this;
    }

    /**
     * Setter for <code>book.member_base_info.register_trace_source</code>. 注册来源码
     */
    public MemberBaseInfoRecord setRegisterTraceSource(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.register_client</code>. 注册客户端
     */
    public Long getRegisterClient() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>book.member_base_info.register_client</code>. 注册客户端
     */
    public MemberBaseInfoRecord setRegisterClient(Long value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.register_trace_source</code>. 注册来源码
     */
    public String getRegisterTraceSource() {
        return (String) get(11);
    }

    /**
     * Getter for <code>book.member_base_info.register_trace_no</code>. 注册来源码编号
     */
    public String getRegisterTraceNo() {
        return (String) get(12);
    }

    /**
     * Setter for <code>book.member_base_info.register_trace_no</code>. 注册来源码编号
     */
    public MemberBaseInfoRecord setRegisterTraceNo(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.register_time</code>. 注册时间
     */
    public Timestamp getRegisterTime() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>book.member_base_info.register_time</code>. 注册时间
     */
    public MemberBaseInfoRecord setRegisterTime(Timestamp value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.register_ip</code>. 注册ip
     */
    public String getRegisterIp() {
        return (String) get(14);
    }

    /**
     * Setter for <code>book.member_base_info.register_ip</code>. 注册ip
     */
    public MemberBaseInfoRecord setRegisterIp(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(15);
    }

    /**
     * Setter for <code>book.member_base_info.remark</code>. 备注
     */
    public MemberBaseInfoRecord setRemark(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>book.member_base_info.create_at</code>. 创建时间
     */
    public MemberBaseInfoRecord setCreateAt(Timestamp value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(17);
    }

    /**
     * Setter for <code>book.member_base_info.update_at</code>. 更新时间
     */
    public MemberBaseInfoRecord setUpdateAt(Timestamp value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_info.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>book.member_base_info.del_flag</code>. 删除标志
     */
    public MemberBaseInfoRecord setDelFlag(Boolean value) {
        set(18, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>book.member_base_info.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>book.member_base_info.version</code>. 版本号
     */
    public MemberBaseInfoRecord setVersion(Long value) {
        set(19, value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MemberBaseInfo.MEMBER_BASE_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MemberBaseInfo.MEMBER_BASE_INFO.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<MemberBaseInfoStatus> field3() {
        return MemberBaseInfo.MEMBER_BASE_INFO.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, Long, MemberBaseInfoStatus, Timestamp, MemberBaseInfoSex, Timestamp, String, String, String, String, Long, String, String, Timestamp, String, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Long, Long, MemberBaseInfoStatus, Timestamp, MemberBaseInfoSex, Timestamp, String, String, String, String, Long, String, String, Timestamp, String, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return MemberBaseInfo.MEMBER_BASE_INFO.TIME_PAYMENT_END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<MemberBaseInfoSex> field5() {
        return MemberBaseInfo.MEMBER_BASE_INFO.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return MemberBaseInfo.MEMBER_BASE_INFO.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MemberBaseInfo.MEMBER_BASE_INFO.TRUE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MemberBaseInfo.MEMBER_BASE_INFO.IDENTITY_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MemberBaseInfo.MEMBER_BASE_INFO.SHORT_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return MemberBaseInfo.MEMBER_BASE_INFO.AVATAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field11() {
        return MemberBaseInfo.MEMBER_BASE_INFO.REGISTER_CLIENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return MemberBaseInfo.MEMBER_BASE_INFO.REGISTER_TRACE_SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return MemberBaseInfo.MEMBER_BASE_INFO.REGISTER_TRACE_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return MemberBaseInfo.MEMBER_BASE_INFO.REGISTER_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return MemberBaseInfo.MEMBER_BASE_INFO.REGISTER_IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return MemberBaseInfo.MEMBER_BASE_INFO.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return MemberBaseInfo.MEMBER_BASE_INFO.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field18() {
        return MemberBaseInfo.MEMBER_BASE_INFO.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoStatus component3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field19() {
        return MemberBaseInfo.MEMBER_BASE_INFO.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field20() {
        return MemberBaseInfo.MEMBER_BASE_INFO.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getTimePaymentEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoSex component5() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTrueName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getIdentityNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getShortUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component11() {
        return getRegisterClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getRegisterTraceSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getRegisterTraceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getRegisterTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getRegisterIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component18() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoStatus value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component19() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component20() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getTimePaymentEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoSex value5() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTrueName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIdentityNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getShortUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value11() {
        return getRegisterClient();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getRegisterTraceSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getRegisterTraceNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getRegisterTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getRegisterIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value18() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value2(Long value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value3(MemberBaseInfoStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value19() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value20() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value4(Timestamp value) {
        setTimePaymentEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value5(MemberBaseInfoSex value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value6(Timestamp value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value7(String value) {
        setTrueName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value8(String value) {
        setIdentityNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value9(String value) {
        setShortUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value10(String value) {
        setAvatar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value11(Long value) {
        setRegisterClient(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value12(String value) {
        setRegisterTraceSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value13(String value) {
        setRegisterTraceNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value14(Timestamp value) {
        setRegisterTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value15(String value) {
        setRegisterIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value16(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value17(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value18(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value19(Boolean value) {
        setDelFlag(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord value20(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseInfoRecord values(Long value1, Long value2, MemberBaseInfoStatus value3, Timestamp value4, MemberBaseInfoSex value5, Timestamp value6, String value7, String value8, String value9, String value10, Long value11, String value12, String value13, Timestamp value14, String value15, String value16, Timestamp value17, Timestamp value18, Boolean value19, Long value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }
}
