/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain.tables.records;


import com.book.core.domain.tables.MemberBaseRefer;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * 会员推荐表
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MemberBaseReferRecord extends UpdatableRecordImpl<MemberBaseReferRecord> implements Record10<Long, Long, Long, Integer, Boolean, String, Timestamp, Timestamp, Boolean, Long> {

    private static final long serialVersionUID = 186884436;

    /**
     * Setter for <code>book.member_base_refer.id</code>. 主键
     */
    public MemberBaseReferRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Create a detached MemberBaseReferRecord
     */
    public MemberBaseReferRecord() {
        super(MemberBaseRefer.MEMBER_BASE_REFER);
    }

    /**
     * Setter for <code>book.member_base_refer.member_id</code>. 会员id
     */
    public MemberBaseReferRecord setMemberId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Create a detached, initialised MemberBaseReferRecord
     */
    public MemberBaseReferRecord(Long id, Long memberId, Long referralId, Integer level, Boolean archived, String remark, Timestamp createAt, Timestamp updateAt, Boolean delFlag, Long version) {
        super(MemberBaseRefer.MEMBER_BASE_REFER);

        set(0, id);
        set(1, memberId);
        set(2, referralId);
        set(3, level);
        set(4, archived);
        set(5, remark);
        set(6, createAt);
        set(7, updateAt);
        set(8, delFlag);
        set(9, version);
    }

    /**
     * Setter for <code>book.member_base_refer.referral_id</code>. 推荐人id
     */
    public MemberBaseReferRecord setReferralId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_refer.id</code>. 主键
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>book.member_base_refer.level</code>. 推荐等级
     */
    public MemberBaseReferRecord setLevel(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_refer.member_id</code>. 会员id
     */
    public Long getMemberId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>book.member_base_refer.archived</code>. 激活标志
     */
    public MemberBaseReferRecord setArchived(Boolean value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_refer.referral_id</code>. 推荐人id
     */
    public Long getReferralId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>book.member_base_refer.remark</code>. 备注
     */
    public MemberBaseReferRecord setRemark(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_refer.level</code>. 推荐等级
     */
    public Integer getLevel() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>book.member_base_refer.create_at</code>. 创建时间
     */
    public MemberBaseReferRecord setCreateAt(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_refer.archived</code>. 激活标志
     */
    public Boolean getArchived() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>book.member_base_refer.update_at</code>. 更新时间
     */
    public MemberBaseReferRecord setUpdateAt(Timestamp value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>book.member_base_refer.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(5);
    }

    /**
     * Getter for <code>book.member_base_refer.create_at</code>. 创建时间
     */
    public Timestamp getCreateAt() {
        return (Timestamp) get(6);
    }

    /**
     * Getter for <code>book.member_base_refer.del_flag</code>. 删除标志
     */
    public Boolean getDelFlag() {
        return (Boolean) get(8);
    }

    /**
     * Getter for <code>book.member_base_refer.update_at</code>. 更新时间
     */
    public Timestamp getUpdateAt() {
        return (Timestamp) get(7);
    }

    /**
     * Getter for <code>book.member_base_refer.version</code>. 版本号
     */
    public Long getVersion() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, Integer, Boolean, String, Timestamp, Timestamp, Boolean, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Long, Long, Long, Integer, Boolean, String, Timestamp, Timestamp, Boolean, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MemberBaseRefer.MEMBER_BASE_REFER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MemberBaseRefer.MEMBER_BASE_REFER.MEMBER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return MemberBaseRefer.MEMBER_BASE_REFER.REFERRAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MemberBaseRefer.MEMBER_BASE_REFER.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return MemberBaseRefer.MEMBER_BASE_REFER.ARCHIVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MemberBaseRefer.MEMBER_BASE_REFER.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MemberBaseRefer.MEMBER_BASE_REFER.CREATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return MemberBaseRefer.MEMBER_BASE_REFER.UPDATE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field9() {
        return MemberBaseRefer.MEMBER_BASE_REFER.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return MemberBaseRefer.MEMBER_BASE_REFER.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getReferralId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getArchived();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component9() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getMemberId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getReferralId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getArchived();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value9() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value2(Long value) {
        setMemberId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value3(Long value) {
        setReferralId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value4(Integer value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value5(Boolean value) {
        setArchived(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value6(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value7(Timestamp value) {
        setCreateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value8(Timestamp value) {
        setUpdateAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value9(Boolean value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord value10(Long value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberBaseReferRecord values(Long value1, Long value2, Long value3, Integer value4, Boolean value5, String value6, Timestamp value7, Timestamp value8, Boolean value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>book.member_base_refer.del_flag</code>. 删除标志
     */
    public MemberBaseReferRecord setDelFlag(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Setter for <code>book.member_base_refer.version</code>. 版本号
     */
    public MemberBaseReferRecord setVersion(Long value) {
        set(9, value);
        return this;
    }
}
