/*
 * This file is generated by jOOQ.
 */
package com.book.core.domain;


import com.book.core.domain.tables.MessageCaptcha;
import com.book.core.domain.tables.SpiderAuthorBaseInfo;
import com.book.core.domain.tables.SpiderBookBaseInfo;
import com.book.core.domain.tables.SpiderBookDetailInfo;
import com.book.core.domain.tables.records.MessageCaptchaRecord;
import com.book.core.domain.tables.records.SpiderAuthorBaseInfoRecord;
import com.book.core.domain.tables.records.SpiderBookBaseInfoRecord;
import com.book.core.domain.tables.records.SpiderBookDetailInfoRecord;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>book</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.10.8"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MessageCaptchaRecord, Long> IDENTITY_MESSAGE_CAPTCHA = Identities0.IDENTITY_MESSAGE_CAPTCHA;
    public static final Identity<SpiderAuthorBaseInfoRecord, Long> IDENTITY_SPIDER_AUTHOR_BASE_INFO = Identities0.IDENTITY_SPIDER_AUTHOR_BASE_INFO;
    public static final Identity<SpiderBookBaseInfoRecord, Long> IDENTITY_SPIDER_BOOK_BASE_INFO = Identities0.IDENTITY_SPIDER_BOOK_BASE_INFO;
    public static final Identity<SpiderBookDetailInfoRecord, Long> IDENTITY_SPIDER_BOOK_DETAIL_INFO = Identities0.IDENTITY_SPIDER_BOOK_DETAIL_INFO;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MessageCaptchaRecord> KEY_MESSAGE_CAPTCHA_PRIMARY = UniqueKeys0.KEY_MESSAGE_CAPTCHA_PRIMARY;
    public static final UniqueKey<SpiderAuthorBaseInfoRecord> KEY_SPIDER_AUTHOR_BASE_INFO_PRIMARY = UniqueKeys0.KEY_SPIDER_AUTHOR_BASE_INFO_PRIMARY;
    public static final UniqueKey<SpiderAuthorBaseInfoRecord> KEY_SPIDER_AUTHOR_BASE_INFO_UNIQUE_NAME = UniqueKeys0.KEY_SPIDER_AUTHOR_BASE_INFO_UNIQUE_NAME;
    public static final UniqueKey<SpiderBookBaseInfoRecord> KEY_SPIDER_BOOK_BASE_INFO_PRIMARY = UniqueKeys0.KEY_SPIDER_BOOK_BASE_INFO_PRIMARY;
    public static final UniqueKey<SpiderBookBaseInfoRecord> KEY_SPIDER_BOOK_BASE_INFO_UNIQ_AUTHORID_TITLE = UniqueKeys0.KEY_SPIDER_BOOK_BASE_INFO_UNIQ_AUTHORID_TITLE;
    public static final UniqueKey<SpiderBookDetailInfoRecord> KEY_SPIDER_BOOK_DETAIL_INFO_PRIMARY = UniqueKeys0.KEY_SPIDER_BOOK_DETAIL_INFO_PRIMARY;
    public static final UniqueKey<SpiderBookDetailInfoRecord> KEY_SPIDER_BOOK_DETAIL_INFO_UNIQUE_BOOK_CHAPTER = UniqueKeys0.KEY_SPIDER_BOOK_DETAIL_INFO_UNIQUE_BOOK_CHAPTER;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<MessageCaptchaRecord, Long> IDENTITY_MESSAGE_CAPTCHA = Internal.createIdentity(MessageCaptcha.MESSAGE_CAPTCHA, MessageCaptcha.MESSAGE_CAPTCHA.ID);
        public static Identity<SpiderAuthorBaseInfoRecord, Long> IDENTITY_SPIDER_AUTHOR_BASE_INFO = Internal.createIdentity(SpiderAuthorBaseInfo.SPIDER_AUTHOR_BASE_INFO, SpiderAuthorBaseInfo.SPIDER_AUTHOR_BASE_INFO.ID);
        public static Identity<SpiderBookBaseInfoRecord, Long> IDENTITY_SPIDER_BOOK_BASE_INFO = Internal.createIdentity(SpiderBookBaseInfo.SPIDER_BOOK_BASE_INFO, SpiderBookBaseInfo.SPIDER_BOOK_BASE_INFO.ID);
        public static Identity<SpiderBookDetailInfoRecord, Long> IDENTITY_SPIDER_BOOK_DETAIL_INFO = Internal.createIdentity(SpiderBookDetailInfo.SPIDER_BOOK_DETAIL_INFO, SpiderBookDetailInfo.SPIDER_BOOK_DETAIL_INFO.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<MessageCaptchaRecord> KEY_MESSAGE_CAPTCHA_PRIMARY = Internal.createUniqueKey(MessageCaptcha.MESSAGE_CAPTCHA, "KEY_message_captcha_PRIMARY", MessageCaptcha.MESSAGE_CAPTCHA.ID);
        public static final UniqueKey<SpiderAuthorBaseInfoRecord> KEY_SPIDER_AUTHOR_BASE_INFO_PRIMARY = Internal.createUniqueKey(SpiderAuthorBaseInfo.SPIDER_AUTHOR_BASE_INFO, "KEY_spider_author_base_info_PRIMARY", SpiderAuthorBaseInfo.SPIDER_AUTHOR_BASE_INFO.ID);
        public static final UniqueKey<SpiderAuthorBaseInfoRecord> KEY_SPIDER_AUTHOR_BASE_INFO_UNIQUE_NAME = Internal.createUniqueKey(SpiderAuthorBaseInfo.SPIDER_AUTHOR_BASE_INFO, "KEY_spider_author_base_info_UNIQUE_NAME", SpiderAuthorBaseInfo.SPIDER_AUTHOR_BASE_INFO.NAME);
        public static final UniqueKey<SpiderBookBaseInfoRecord> KEY_SPIDER_BOOK_BASE_INFO_PRIMARY = Internal.createUniqueKey(SpiderBookBaseInfo.SPIDER_BOOK_BASE_INFO, "KEY_spider_book_base_info_PRIMARY", SpiderBookBaseInfo.SPIDER_BOOK_BASE_INFO.ID);
        public static final UniqueKey<SpiderBookBaseInfoRecord> KEY_SPIDER_BOOK_BASE_INFO_UNIQ_AUTHORID_TITLE = Internal.createUniqueKey(SpiderBookBaseInfo.SPIDER_BOOK_BASE_INFO, "KEY_spider_book_base_info_uniq_authorid_title", SpiderBookBaseInfo.SPIDER_BOOK_BASE_INFO.AUTHOR_ID, SpiderBookBaseInfo.SPIDER_BOOK_BASE_INFO.TITLE);
        public static final UniqueKey<SpiderBookDetailInfoRecord> KEY_SPIDER_BOOK_DETAIL_INFO_PRIMARY = Internal.createUniqueKey(SpiderBookDetailInfo.SPIDER_BOOK_DETAIL_INFO, "KEY_spider_book_detail_info_PRIMARY", SpiderBookDetailInfo.SPIDER_BOOK_DETAIL_INFO.ID);
        public static final UniqueKey<SpiderBookDetailInfoRecord> KEY_SPIDER_BOOK_DETAIL_INFO_UNIQUE_BOOK_CHAPTER = Internal.createUniqueKey(SpiderBookDetailInfo.SPIDER_BOOK_DETAIL_INFO, "KEY_spider_book_detail_info_UNIQUE_BOOK_CHAPTER", SpiderBookDetailInfo.SPIDER_BOOK_DETAIL_INFO.BOOK_ID, SpiderBookDetailInfo.SPIDER_BOOK_DETAIL_INFO.CHAPTER_TITLE);
    }
}
